up(bin/docs): update docs; now it's more interactive

diff --git a/bin/docs b/bin/docs
--- a/bin/docs
+++ b/bin/docs
@@ -1,51 +1,131 @@
 #!/usr/bin/bash
 
-function usage {
-  echo "Usage:       docs [wiki|journal|project] [-p project] [-e editor] [-c command...]"
-  echo "Description: Writes documentation on local document repositories"
-  echo "Commands:
-  on \`wiki': <path>
-  on \`journal': <yy><mm>"
-  exit 1
-}
+case $1 in
+  '-h'|'--help'|'')
+    echo "Usage:       docs [-iI] [wiki|journal|project]:[command...] [editor...]"
+    echo "Description: Writes documentation on local document repositories"
+    echo "Options:
+  Pre-mode:
+    -i: launch interactive (fzf-like command)
+    -I: launch interactive (dmenu-like command)
 
+  Post-mode:
+    <mode>: choose the mode to run \`docs' with
+    <command>: run command of <mode>
+      command syntax for mode:
+        on \`wiki': <file-path--org>
+        on \`journal': <yy><mm>
+        on \`project': <project>:<file-path--org>
+    <editor>: editor command to use"
+    echo "Environment:
+  EDITOR: editor command
+  DMENU: dmenu-like command for \`-i'
+  FZF: fzf-like command for \`-I'"
+  exit 1;;
+esac
+
+### BEGIN: CONSTS ###
 WIKI="/home/mh/Documents/Org/Wiki"
 JOURNAL="/home/mh/Documents/Org/Journal"
 PROJECT="/home/mh/Git/MH"
+### END: CONSTS ###
 
+### BEGIN: VARS ###
 REPO=''
 EDITOR=''
+INT='' # i->fzf,I->dmenu
+### END: VARS ###
 
-case $1 in
-  '-h'|'--help')
-    usage;;
-esac
 
-[[ -z $1 ]] && usage
-
-function do_defaults {
-  [[ -z $EDITOR ]] && EDITOR=emacsxc
-  [[ -z $REPO ]]   && REPO=$WIKI/index.org
-}
-
+### BEGIN: COMMANDS ###
 function wikicmd {
-  REPO+="/$1.org"
+  if [[ -z $1 ]]; then
+    # let interactive-mode figure it out
+    if [[ ! -z $INT ]]; then
+      return 0
+    fi
+
+    echo "[ WW ] Missing command for \`wiki-mode'; defaulting to index"
+    FILE=index
+  else
+    if [[ ! -z $INT ]]; then
+      echo "[ !! ] \`interactive-mode' with existing mode is not supported"
+      exit 1
+    fi
+
+    FILE=$1
+  fi
+
+  if [[ -d $REPO/$FILE ]]; then
+    REPO+="/$FILE"
+  else
+    REPO+="/$FILE.org"
+  fi
+
 }
 
 function projectcmd {
-  REPO+="/$1.org"
+  if [[ -z $1 ]]; then
+    # let interactive-mode figure it out
+    if [[ ! -z $INT ]]; then
+      return 0
+    fi
+
+    echo "[ !! ] Missing command for \`project-mode'; defaulting \`project-mode' is not supported"
+    exit 1
+  else
+    if [[ ! -z $INT ]]; then
+      echo "[ !! ] \`interactive-mode' with existing mode is not supported"
+      exit 1
+    fi
+  fi
+
+  local repo=${1%%:*}
+  local file=${1#*:}
+
+  if [[ $repo = $file ]]; then
+    file=''
+  fi
+
+  if [[ -z $file ]]; then
+    file="dev/index.org"
+  elif [[ -d $file ]]; then
+    file="dev/$file"
+  else
+    file="dev/$file.org"
+  fi
+
+  REPO+="/$repo/$file"
 }
 
 function journalcmd {
+  if [[ -z $1 ]]; then
+
+    # let interactive-mode figure it out
+    if [[ ! -z $INT ]]; then
+      return 0
+    fi
+
+    echo "[ WW ] Missing command for \`journal-mode'; defaulting to current date"
+    DATE=$(date +'%y%m')
+  else
+    if [[ ! -z $INT ]]; then
+      echo "[ !! ] \`interactive-mode' with existing mode is not supported"
+      exit 1
+    fi
+
+    DATE=$1
+  fi
+
   local yy= mm=
 
   while :; do
-    if (( ${#1} != 4 )); then
+    if (( ${#DATE} != 4 )); then
       break
     fi
 
-    yy=${1:0:2}
-    mm=${1:2:2}
+    yy=${DATE:0:2}
+    mm=${DATE:2:2}
 
     [[ -d $REPO/20$yy/ ]]        || break
     [[ -f $REPO/20$yy/$mm.org ]] || break
@@ -58,85 +138,76 @@ function journalcmd {
   echo "[ !! ] Command doesn't evaluate"
   exit 1
 }
+### END: COMMANDS ###
 
-function handle {
-  local repo=$1
-
-  case $repo in
-    'wiki')
-      REPO=$WIKI;;
-    'journal')
-      REPO=$JOURNAL;;
-    'project')
-      REPO=$PROJECT;;
-  esac
-
-  local _editor=false      \
-        _cmd=false         \
-        _project=false     \
-        _did_cmd=false     \
-        _did_project=false
-
-  for opt in ${@:1}; do
-    if [[ $opt = '-c' ]]; then
-      _cmd=true
-      _editor=false
-      _project=false
-      continue
-    elif [[ $opt = '-p' ]]; then
-      _cmd=false
-      _project=true
-      continue
-    elif [[ $opt = '-e' ]]; then
-      _cmd=false
-      _project=false
-      _editor=true
-      continue
-    fi
-
-    if $_editor; then
-      EDITOR+=" $opt"
-    elif $_project; then
-      REPO+="/$opt/dev"
-      _did_project=true
-    elif $_cmd; then
-      local cmd=$opt
-      case $repo in
-        'wiki')
-          _did_cmd=true
-          wikicmd $cmd;;
-        'journal')
-          _did_cmd=true
-          journalcmd $cmd;;
-        'project')
-          _did_cmd=true
-          projectcmd $cmd;;
-      esac
-    fi
-  done
-
-  if [[ $repo = 'project' ]] && ! $_did_project; then
-    echo "[ !! ] Missing project"
-    exit 1
-  fi
-
-  if ! $_did_cmd; then
-    REPO+="/index.org"
-  fi
-}
+off=
 
 case $1 in
-  'wiki')
-    handle ${@:1};;
-  'journal')
-    handle ${@:1};;
-  'project')
-    handle ${@:1};;
+  '-i')
+    off=3
+    mode_arg=$2
+    [[ -z $FZF ]] && FZF=fzf
+    INT=$FZF;;
+  '-I')
+    off=3
+    mode_arg=$2
+    [[ -z $DMENU ]] && DMENU='dmenu -p choose'
+    INT=$DMENU;;
   *)
-    echo "[ !! ] Invalid entry"
+    off=2
+    mode_arg=$1;;
+esac
+
+mode=${mode_arg%%:*}
+cmd=${mode_arg#*:}
+
+# there is no `:'
+if [[ $cmd = $mode ]]; then
+  cmd=''
+fi
+
+case $mode in
+  'wiki')
+    REPO=$WIKI
+    wikicmd ${cmd};;
+  'journal')
+    REPO=$JOURNAL
+    journalcmd ${cmd};;
+  'project')
+    REPO=$PROJECT
+    projectcmd ${cmd};;
+  *)
+    echo "[ !! ] Invalid mode"
     exit 1;;
 esac
 
-do_defaults
+EDITOR=${@:off}
 
+# default to emacs
+[[ -z $EDITOR ]] && EDITOR=emacs
+
+function feed {
+ ans=$(echo "$@" | $INT)
+
+ if [[ -z $ans ]]; then
+   echo "[ !! ] Missing command: \`interactive-mode' returned nil"
+   exit 1
+ fi
+
+ echo $ans
+}
+
+if [[ ! -z $INT ]]; then
+  case $mode in
+    'wiki')
+      REPO=$(feed "$(find $REPO -type f -name '*.org')");;
+    'journal')
+      REPO=$(feed "$(find $REPO -type f -name '[0-9][0-9].org')");;
+    'project')
+      REPO=$(feed "$(find $REPO/*/dev -type f -name '*.org')");;
+  esac
+fi
+
+# DEBUG
+echo "[ == ] Running as: $EDITOR $REPO"
 exec $EDITOR $REPO
