up(killpid): add a `ps` switch that keeps the PIDFILE if the process was not
  killed properly with `SIGTERM`

diff --git a/killpid b/killpid
--- a/killpid
+++ b/killpid
@@ -14,5 +14,13 @@ PID=$(cat $PIDFILE)
 
 echo "[ == ] kill ${KILL_OPTIONS:--TERM} $PID"
 
-kill ${KILL_OPTIONS:--TERM} $PID &&
+kill ${KILL_OPTIONS:--TERM} $PID
+sleep 3
+
+if [[ -z $(ps -p $PID | sed -n 2p) ]]; then
+  echo "[ .. ] Done: killed process, removing PIDFILE"
   rm $PIDFILE
+else
+  echo "[ !! ] Error: process was not killed"
+  exit 1
+fi
